### ISSUE TITLE
Conversion de inner_functions en loop_body dans prob_rep

### ISSUE THREAD

**Issue by rdang-nhu** [victornicolet/parsynt#11]
```
type prob_rep =
  {
    id : int;
    host_function : func_dec;
    loop_name : string;
    scontext : context;
    min_input_size : int;
    uses_global_bound : bool;
    main_loop_body : fnExpr;
    loop_body_versions : fnExpr SH.t;
    join_sketch : fnExpr;
    memless_sketch : fnExpr;
    join_solution : fnExpr;
    memless_solution : fnExpr;
    init_values : RAst.expr IM.t;
    identity_values : constants IM.t;
    func_igu : sigu;
    reaching_consts : fnExpr IM.t;
    inner_functions : prob_rep list;
}

 | FnRec of (fnExpr * fnExpr * fnExpr) * (VarSet.t * fnExpr) * (fnV * fnExpr)
```
Quelles sont les conversions à faire pour transformer le _inner_functions_ en _main_loop_body_ ?
Pour l'instant je vois surtout `problem.main_loop_body := FnRec ...` Est-ce qu'il y a d'autres choses à changer ? Peut-être aussi dans  join_sketch. 
Au fond je crois que j'aurais besoin que tu m'écrives la description de chaque entrée de `prob_rep` ainsi que de `FnRec`. On en a un peu parlé ce matin mais je n'ai pas tout.

**Comment by victornicolet** [comment]
I added a comment for a function that you might want to use, as well as comments for each of the `prob_rep` fields.
